[package]
name = "grokking-rust"
version = "0.0.1"
authors = [ "" ]

[[bin]]
name = "grokking-rust"

[dependencies]
log = "0.3"
env_logger = "0.3"
quickcheck = "0.2"

[dev-dependencies]

[workspace]
members = [
  "crates/trampoline",
  "crates/trampoline_tests",
]